server:
    port: 8083


spring:
    # profiles: dev
    application:
        name: bank
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bankapp
        username: root
        password: 
# ---
# spring:
#     profiles: qa
#     application:
#         name: bank
        
#     jpa:
#         hibernate:
#             ddl-auto: update
#         show-sql: true
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQLDialect
#     datasource:
#         driver-class-name: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://localhost:3306/bankapp
#         username: root
#         password: 



# ---
# spring:
#     profiles: prod
#     application:
#         name: bank
        
#     jpa:
#         hibernate:
#             ddl-auto: update
#         show-sql: true
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQLDialect
#     datasource:
#         driver-class-name: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://localhost:3306/bankapp
#         username: root
#         password: 


